n1 = input("Enter anything: ")
print(" ")
print("Number type:",type(n1))
print("Does this input have only spaces?: ",n1.isspace())
print("Is this input numeric?: ",n1.isnumeric())
print("Is this input alphabetic?: ",n1.isalpha())
print("Is this input alphanumeric?: ",n1.isalnum())
print("Is this input an upper case?: ",n1.isupper())
print("Is this input a lower case?: ",n1.islower())
