sentence = "Curso em Video Python"
sentenceSplit = "   Curso em Video Python   "
print(sentence)
print(sentence[3])
print(sentence[3:13])
print(sentence[:13])
print(sentence[13:])
print(sentence[1:15])
print(sentence[1:15:2])
print(sentence[::2])
print(sentence.count('o'))
print(sentence.count('O'))
print(sentence.upper().count('O'))
print(len(sentence))
print(len(sentenceSplit))
print(len(sentenceSplit.strip()))
print(sentence.replace("Python","Android"))
print(sentence[0])
print('Curso' in sentence)
print(sentence.find('Curso'))
print(sentence.find('Video'))
print(sentence.find('video'))
print(sentence.lower().find('video'))
print(sentence.split())
division = sentence.split()
print(division[0])
print(division[2][3])
print(sentence.rfind("P"))
print(" ")
print("========================================================================================================================================================================")
print("""Freida Selena Pinto (born 18 October 1984) is an Indian actress who has appeared mainly in American and British films. 
Born and raised in Mumbai, India, she resolved, at a young age, to become an actress. 
As a student at St. Xavier's College, Mumbai, she took part in amateur plays. After graduation, she briefly worked as a model and then as a television presenter. """)
print("===========================================================================================================================================================================")
print(" ")

freida = """Freida Selena Pinto (born 18 October 1984) is an Indian actress who has appeared mainly in American and British films. 
Born and raised in Mumbai, India, she resolved, at a young age, to become an actress. 
As a student at St. Xavier's College, Mumbai, she took part in amateur plays. After graduation, she briefly worked as a model and then as a television presenter."""

print(freida[3])
print(freida[3:13])
print(freida[:13])
print(" ")
print(freida[13:])
print(" ")
print(freida[1:15])
print(freida[1:15:2])
print(" ")
print(freida[::2])
print(" ")
print(freida.count('o'))
print(freida.count('O'))
print(freida.upper().count('O'))
print(len(freida))
print(" ")
print(freida.replace("Selena","Bitch"))
print(" ")
print(freida[0])
print("British" in freida)
print(freida.find("Pinto"))
print(freida.find("Model"))
print(freida.find("model"))
print(freida.upper().find("model"))